### ISSUE TITLE
尝试推断图床端转换后的文件类型

### ISSUE THREAD

**Issue by chengzhongxue** [ichenhe/halo-lsky-pro#3]
由于 Lsky Pro 限制，若启用图床端格式转换（图片压缩）将导致 Halo 中显示的附件大小或文件类型不正确

**Comment by ichenhe** [comment]
文件类型可以尝试从返回 url 中推断一下，文件大小不好弄。除非当场下载一遍计算大小，感觉不值。就算作为一个可选项也有点潦草。

**Comment by chengzhongxue** [comment]
> 文件类型可以尝试从返回 url 中推断一下，文件大小不好弄。除非当场下载一遍计算大小，感觉不值。就算作为一个可选项也有点潦草。

那就忘记类型弄对就行了，文件大小应该不影响什么吧
