### ISSUE TITLE
上传错了，验证是成功的

### ISSUE THREAD

**Issue by chengzhongxue** [ichenhe/halo-lsky-pro#4]
java.lang.NullPointerException: Cannot invoke "me.chenhe.halo.lskypro.client.Links.url()" because the return value of "me.chenhe.halo.lskypro.client.UploadResponse.links()" is null
	at me.chenhe.halo.lskypro.LskyProAttachmentHandler.buildAttachment(LskyProAttachmentHandler.java:140) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:

**Comment by ichenhe** [comment]
有点奇怪，可以做一下空判断，但依然是失败，这种事不应该发生。
提供的日志无法判断为什么 lsky pro 没有返回图片链接。

**Comment by chengzhongxue** [comment]
> 有点奇怪，可以做一下空判断，但依然是失败，这种事不应该发生。 提供的日志无法判断为什么 lsky pro 没有返回图片链接。



> 有点奇怪，可以做一下空判断，但依然是失败，这种事不应该发生。 提供的日志无法判断为什么 lsky pro 没有返回图片链接。

这什么问题啊，我上传图片就这样，好像就这个日志 其他的我就不知道了

**Comment by ichenhe** [comment]
你方便的话可以 debug 一下，看看 lskypro 到底返回了啥。我会在日志里尽可能加一些其他信息。

**Comment by yushuiguozhi** [comment]
可以上传成功打开链接也是没问题，预览界面异常的
![image](https://github.com/ichenhe/halo-lsky-pro/assets/100274978/521665fd-959c-4976-8131-bd4a3fbc373e)
![D34FA7E6-6EF2-47ce-AB4A-18877FF6700B](https://github.com/ichenhe/halo-lsky-pro/assets/100274978/d7653b91-c67c-44c2-b35d-6e30cdeef2a1)

**Comment by ichenhe** [comment]
你的意思是上传成功，前台没有报错。只是预览异常，然后后台出现错误日志？

**Comment by yushuiguozhi** [comment]
> 你的意思是上传成功，前台没有报错。只是预览异常，然后后台出现错误日志？

嗯，可以上传成功，显示异常，

**Comment by ichenhe** [comment]
如果插件没有报错（无论前台还是后台），图片url也正确，就是 halo 中无法显示，建议检查 lsky pro 的配置，例如防盗链啥的。

**Comment by yushuiguozhi** [comment]
> 如果插件没有报错（无论前台还是后台），图片url也正确，就是 halo 中无法显示，建议检查 lsky pro 的配置，例如防盗链啥的。

en ,都是默认配置。

**Comment by ichenhe** [comment]
此问题无法复现，所提供日志表明 Lsky Pro 上传图片接口的响应不包含 `links` 字段，理论上不会发生的。v0.2.1 已对此做了额外判断提供更明确的错误信息，但未修复。

建议：
- 手动 debug 插件，查看 Lsky Pro 的返回值。
- 若图片 URL 正常但 Halo 中无法访问建议查看 Lsky Pro 的网络配置，防盗链规则等。

此 issue 目前视为无效，若有进一步错误日志或其他证据表明与本插件有关欢迎重新打开。

**Comment by yushuiguozhi** [comment]
> 此问题无法复现，所提供日志表明 Lsky Pro 上传图片接口的响应不包含 `links` 字段，理论上不会发生的。v0.2.1 已对此做了额外判断提供更明确的错误信息，同时在验证时也打印了 Lsky Pro 的具体响应，但未修复。
> 
> 建议：
> 
> * 手动 debug 插件，查看 Lsky Pro 的返回值 ([`client/LskyProClient.java#upload`](https://github.com/ichenhe/halo-lsky-pro/blob/cf40eee8cee6a6068d88fb89d8647950733a3aca/src/main/java/me/chenhe/halo/lskypro/client/LskyProClient.java#L74))。
> * 若图片 URL 正常但 Halo 中无法显示，建议首先查看显示的图片的 URL，其次查看 Lsky Pro 的网络配置，防盗链规则等。
> 
> 此 issue 目前视为无效，若有进一步错误日志或其他证据表明与本插件有关欢迎重新打开。

![image](https://github.com/ichenhe/halo-lsky-pro/assets/100274978/ab465a17-6edc-4714-8a14-3db750ce2048)
wo我看知乎上有人提这个，会不会这个原因 https://zhuanlan.zhihu.com/p/628263030
![image](https://github.com/ichenhe/halo-lsky-pro/assets/100274978/b79eb450-f0d9-4246-afbc-9dd54d6af7f8)

**Comment by chengzhongxue** [comment]
> java.lang.NullPointerException: Cannot invoke "me.chenhe.halo.lskypro.client.Links.url()" because the return value of "me.chenhe.halo.lskypro.client.UploadResponse.links()" is null at me.chenhe.halo.lskypro.LskyProAttachmentHandler.buildAttachment(LskyProAttachmentHandler.java:140) ~[na:na] Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:

我知道这个问题了，图片审核失败了导致了这个问题

**Comment by chengzhongxue** [comment]
> > java.lang.NullPointerException: Cannot invoke "me.chenhe.halo.lskypro.client.Links.url()" because the return value of "me.chenhe.halo.lskypro.client.UploadResponse.links()" is null at me.chenhe.halo.lskypro.LskyProAttachmentHandler.buildAttachment(LskyProAttachmentHandler.java:140) ~[na:na] Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
> 
> 我知道这个问题了，图片审核失败了导致了这个问题

我设置了图片审核

**Comment by ichenhe** [comment]
@yushuiguozhi 

不会。CORS 将导致 API 请求直接失败，不会返回 http 200 状态码。更不会返回一个基本符合 LskyPro API schema 的响应体。
