### ISSUE TITLE
[Bug] 上传后的图片，在halo控制台上显示加载异常，这是什么问题呢

### ISSUE THREAD

**Issue by xiaopengzzc** [ichenhe/halo-lsky-pro#5]
### Environment

- Halo version: 2.15.0-rc.1
- Plugin version: 0.2.1

### Description

上传后的图片，在halo控制台上显示加载异常，这是什么问题呢，上传是成功的，就是浏览图片的时候
![Clip_2024-04-30_10-24-21](https://github.com/ichenhe/halo-lsky-pro/assets/136769452/68964d3e-de89-469a-8f00-09d7fd063415)
![Clip_2024-04-30_10-25-35](https://github.com/ichenhe/halo-lsky-pro/assets/136769452/a50c830c-9c5a-4a82-ba6b-111f36e39266)

**Comment by yushuiguozhi** [comment]
遇到问题是一样的

**Comment by 666-GE** [comment]
> 请问是否开启了 LskyPro 的图片审核？
> 
> 可能的相同问题：[#4 (comment)](https://github.com/ichenhe/halo-lsky-pro/issues/4#issuecomment-2084268150)

我也是一样的问题，没开图片审核

**Comment by ichenhe** [comment]
@666-GE 

- 图片 url 直接访问是否正常？
- HTML 代码里能否看到加载异常处的图片地址？
- 前端 f12 是否有任何错误信息？

我一直复现不了这个问题

**Comment by ichenhe** [comment]
有此问题的同学欢迎提供一个你们图床的测试账号给我，注意 LskyPro 后台设置为与发生故障用户相同的用户组。
也可以联系我远程调试，如何愿意自己 debug 就更好了。

可通过邮箱 i@chenhe.me 或 telegram: https://t.me/chenhe 联系我，谢谢

- 地址
- 用户名
- 密码

**Comment by 666-GE** [comment]
> @666-GE
> 
> * 图片 url 直接访问是否正常？
> * HTML 代码里能否看到加载异常处的图片地址？
> * 前端 f12 是否有任何错误信息？
> 
> 我一直复现不了这个问题

图片url可以直接访问，但是直接访问自动下载，我把我的图床账号tg发给你，你试试

**Comment by 666-GE** [comment]
我好像找到了个问题，我去试一下，刚才在F12检查加载异常的时候，显示加载的图片是https的网址，但是兰空没设置ssl，我设置一下试试

**Comment by 666-GE** [comment]
解决了，出现这个问题是因为兰空没有设置ssl，因为在附件详情里加载的图片地址是https协议的，所以如果兰空是http地址的就会加载异常，而且如果是像我一样对接的alist，图片地址不要用dav路径的，dav路径加载图片需要输入账号密码，用/d/路径就可以了。

**Comment by ichenhe** [comment]
此 Issue 中的部分用户已确认解决（与图床 https 配置有关），由于提问者迟迟没有回复，暂时关闭。

若遇到类似问题请按照置顶 Issue #6 的指导自助排查，若依然无法解决请打开新的 Issue。

**Comment by ljq7721** [comment]
> 解决了，出现这个问题是因为兰空没有设置ssl，因为在附件详情里加载的图片地址是https协议的，所以如果兰空是http地址的就会加载异常，而且如果是像我一样对接的alist，图片地址不要用dav路径的，dav路径加载图片需要输入账号密码，用/d/路径就可以了。
/d/路径找不到

**Comment by ichenhe** [comment]
@ljq7721 这属于图床设置问题，我不用 Alist 套娃，抱歉无法帮忙。
